#LOGGING
#logging:
#    config: classpath:config/logback.yml
---
hsweb:
    dynamic-datasource: #动态数据源配置
          url: jdbc:h2:file:./data/h2db;DB_CLOSE_ON_EXIT=FALSE
          username: sa
          password:
          icatch:
            max-actives: 100
            output-dir: ./data/atomikos
            log_base_dir: ./data/atomikos
            default-jta-timeout: 300000
    access-logger: on #开启访问日志
---
file:
  upload:
    dir:  ./temp
---
#redis
# Redis服务器地址
  spring:
    redis:
      host: localhost
# Redis服务器连接端口
      port: 6379
# 连接超时时间（毫秒）
      timeout: 0
# 连接池中的最大空闲连接
      pool:
        max-idle: 8
# 连接池中的最小空闲连接
        min-idle: 0
# 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
 ---
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: wangyue
#    password: skywing