#LOGGING
#logging:
#    config: classpath:config/logback-prod.yml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://localhost:3306/skywing?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: wangyue
    password: skywing
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    logSlowSql: true
    filters: stat,wall,log4j
---
file:
  upload:
    dir:  ./temp
---
freemarker :
#      suffix : .ftl
      request-context-attribute : request
      expose-request-attributes : true
---
#redis
# Redis服务器地址
  spring:
    redis:
      host: localhost
# Redis服务器连接端口
      port: 6379
# 连接超时时间（毫秒）
      timeout: 0
# 连接池中的最大空闲连接
      pool:
        max-idle: 8
# 连接池中的最小空闲连接
        min-idle: 0
# 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1